imageType:
  Original: { }
  Wavelet: { }
  LoG:
    sigma:
      - 1.0
      - 2.0
      - 3.0
  LBP3D: { }

featureClass:
  firstorder:
  glcm:
  glrlm:
  glszm:
  gldm:
  ngtdm:
  shape:

setting:
  voxelArrayShift: 0
  resampledPixelSpacing:
  binWidth: 10